fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_state",
            "take_notice",
            "add_workspace",
            "remove_workspace",
            "rename_workspace",
            "reorder_workspaces",
            "activate_workspace",
            "activate_tab",
            "close_tab",
            "reorder_tabs",
            "set_overlay",
            "clear_browsing_data",
            "set_theme",
            "set_workspace_icon",
            "workspace_menu",
            "tab_menu",
            "apps_menu",
            "reveal_download",
            "retry_tab",
            "nc_report_location",
            "nc_report_meta",
            "nc_report_fullscreen",
        ]),
    ))
    .expect("failed to run tauri-build");
}
